In [ ]:
import torch

if torch.cuda.is_available():
    device = "cuda"
elif torch.backends.mps.is_available():
    device = "mps"
else:
     device = "cpu"

In [ ]:
M = torch.tensor([[1.,2.,3.],[4.,5.,6.]])
M = M.to(device)
print(M)

tensor([[1., 2., 3.],
        [4., 5., 6.]], device='cuda:0')


In [ ]:
M.device


device(type='cuda', index=0)

In [ ]:
M = torch.tensor([[1.,2.,3.],[4.,5.,6.]], device=device)

In [ ]:
R = M @ M.T  # run some operations on the GPU
R

tensor([[14., 32.],
        [32., 77.]], device='cuda:0')

In [ ]:
M = torch.rand(1000,1000) #on cpu
%timeit M@M.T

15.5 ms ± 2.24 ms per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [ ]:
M = torch.rand((1000,1000),device='cuda') #on gpu
%timeit M@M.T

562 µs ± 13.5 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


# auto-differentiation feature.

AutoGrad

In [ ]:
x = torch.tensor(5.0, requires_grad=True)
f = x ** 2
f

tensor(25., grad_fn=<PowBackward0>)

In [ ]:
f.backward()
x.grad


tensor(10.)

In [ ]:
learning_rate = 0.1
with torch.no_grad():
  x -= learning_rate * x.grad #Gradient descent

In [ ]:
x

tensor(4., requires_grad=True)

In [ ]:
import torch
learning_rate=0.1
x =torch.tensor(6.7)
y= torch.tensor(0.0)

In [ ]:
w = torch.tensor(1.0,requires_grad=True)
b = torch.tensor(0.0,requires_grad=True)


In [ ]:
w

tensor(1., requires_grad=True)

In [ ]:
b

tensor(0., requires_grad=True)

In [ ]:
z=w*x + b
z

tensor(6.7000, grad_fn=<AddBackward0>)

In [ ]:
y_pred = torch.sigmoid(z)
y_pred

tensor(0.9988, grad_fn=<SigmoidBackward0>)

In [ ]:
import torch.nn as nn

criterion = nn.BCELoss()
loss = criterion(y_pred, y)
loss

tensor(6.7012, grad_fn=<BinaryCrossEntropyBackward0>)

In [ ]:
loss.backward()

In [ ]:
print(w.grad)
print(b.grad)

tensor(6.6918)
tensor(0.9988)


#vector autogarde

In [ ]:
x = torch.tensor([1.0,2.0,3.0],requires_grad=True)
x

tensor([1., 2., 3.], requires_grad=True)

In [ ]:
y = (x**2).mean()
y

tensor(4.6667, grad_fn=<MeanBackward0>)

In [ ]:
y.backward()

In [ ]:
print(x.grad)

tensor([1.3333, 2.6667, 4.0000])


#cleaning grid

In [ ]:
x = torch.tensor(2.0,requires_grad=True)
y = x**2
y

tensor(4., grad_fn=<PowBackward0>)

In [ ]:
y.backward()

In [ ]:
x.grad

tensor(4.)

In [ ]:
x.grad.zero_()

tensor(0.)

In [ ]:
#disable the gtadient tracking
z = torch.tensor(10.0,requires_grad=True)
z

tensor(10., requires_grad=True)

In [ ]:
y = x**2
y

tensor(4., grad_fn=<PowBackward0>)

In [ ]:
y.backward()

In [ ]:
x.grad

tensor(4.)

# option 1 - requires_grad_(False)
# option 2 - detach()
# option 3 - torch.no_grad()

In [ ]:
#option 1
x.requires_grad_(False)
x



tensor(4.)

In [ ]:
y = x**2
y

tensor(4.)

In [ ]:
y.backward()


RuntimeError: element 0 of tensors does not require grad and does not have a grad_fn

In [ ]:
x = torch.tensor(8.0,requires_grad=True)
x

tensor(8., requires_grad=True)

In [ ]:
z = x.detach()
z

tensor(8.)

In [ ]:
y = x**2
y

tensor(64., grad_fn=<PowBackward0>)

In [ ]:
y1=z**2
y1

tensor(64.)

In [ ]:
y.backward()

In [ ]:
y1.backward()

RuntimeError: element 0 of tensors does not require grad and does not have a grad_fn